version: '3'

services:
  wordpress: # --names
    image: wordpress:latest # IMAGE:TAG
    ports:
      - "60000:80"
    restart: always # 컨테이너 실행 타이밍 문제 해결을 위해 필요
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 1111
    depends_on:
      - mysql
  db:
    image: mysql:5.7
    volumes: # mount
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 1111

volumes: # define volume
  db_data: {}